# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file

version: '3'
services:
  user-auth-service:
    image: user-auth-service
    build:
      context: UserAuthentication-Service/
    restart: always
    network_mode: host
    ports:
      - 8084:8084
    depends_on:
      - user-mysql

  reminder-service:
    image: reminder-service
    build:
      context: ReminderService/
    restart: always
    network_mode: host
    ports:
        - 8083:8083
    depends_on:
        - mongo-service

  note-service:
    image: note-service
    build:
      context: NoteService/
    restart: always
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
      - mongo-service

  category-service:
     image: category-service
     build:
       context: CategoryService/
     restart: always
     network_mode: host
     ports:
       - 8081:8081
     depends_on:
       - mongo-service

  user-service:
     image: user-service
     build:
       context: UserService/
     restart: always
     network_mode: host
     ports:
       - 8085:8085
     depends_on:
       - mongo-service

  user-mysql:
    image: mysql:5.6
    restart: always
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app-root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: test

  mongo-service:
      image: mongo:latest
      command: mongod --port 27018
      network_mode: host
      restart: always
      volumes:
        - /data/dump:/data/db
      ports:
        - 27017:27018
